### ISSUE TITLE
"Bad Key" error when decrypting notification file.

### ISSUE THREAD

**Issue by bfaria15093** [IRSgov/IDES-Data-Preparation-Dot-Net#12]
Hi all,

I'm having the error bad key when i try to decrypt the notification file.

I'm using 2 self signed certificates to sign and encrypt xml file. I'm creating the certificates like this:

                public static X509Certificate2 CreateX509Certificate2(string subjectName = null)
            {
            Guid random = Guid.NewGuid();
            subjectName = string.IsNullOrWhiteSpace(subjectName) ? "CLCert" +            random.ToString().Replace("-", "") : subjectName;

            // create DN for subject and issuer
            var dn = new CX500DistinguishedName();
            dn.Encode("CN=" + subjectName, X500NameFlags.XCN_CERT_NAME_STR_NONE);

            // create a new private key for the certificate
            CX509PrivateKey privateKey = new CX509PrivateKey();
            privateKey.ProviderName = "Microsoft Base Cryptographic Provider v1.0";
            privateKey.MachineContext = true;
            privateKey.Length = 2048;
            privateKey.KeySpec = X509KeySpec.XCN_AT_SIGNATURE; // use is not limited
            privateKey.ExportPolicy = X509PrivateKeyExportFlags.XCN_NCRYPT_ALLOW_PLAINTEXT_EXPORT_FLAG;
            privateKey.Create();

            // Use the stronger SHA512 hashing algorithm
            var hashobj = new CObjectId();
            hashobj.InitializeFromAlgorithmName(ObjectIdGroupId.XCN_CRYPT_HASH_ALG_OID_GROUP_ID,
                ObjectIdPublicKeyFlags.XCN_CRYPT_OID_INFO_PUBKEY_ANY,
                AlgorithmFlags.AlgorithmFlagsNone, "SHA512");

            // add extended key usage if you want - look at MSDN for a list of possible OIDs
            var oid = new CObjectId();
            oid.InitializeFromValue("1.3.6.1.5.5.7.3.1"); // SSL server
            var oidlist = new CObjectIds();
            oidlist.Add(oid);
            var eku = new CX509ExtensionEnhancedKeyUsage();
            eku.InitializeEncode(oidlist);

            // Create the self signing request
            var cert = new CX509CertificateRequestCertificate();
            cert.InitializeFromPrivateKey(X509CertificateEnrollmentContext.ContextMachine, privateKey, "");
            cert.Subject = dn;
            cert.Issuer = dn; // the issuer and the subject are the same
            cert.NotBefore = DateTime.Now;
            // this cert expires immediately. Change to whatever makes sense for you
            cert.NotAfter = DateTime.Now;
            cert.X509Extensions.Add((CX509Extension)eku); // add the EKU
            cert.HashAlgorithm = hashobj; // Specify the hashing algorithm
            cert.Encode(); // encode the certificate

            // Do the final enrollment process
            var enroll = new CX509Enrollment();
            enroll.InitializeFromRequest(cert); // load the certificate
            enroll.CertificateFriendlyName = subjectName; // Optional: add a friendly name
            string csr = enroll.CreateRequest(); // Output the request in base64
                                                 // and install it back as the response
            enroll.InstallResponse(InstallResponseRestrictionFlags.AllowUntrustedCertificate,
                csr, EncodingType.XCN_CRYPT_STRING_BASE64, ""); // no password
                                                                // output a base64 encoded PKCS#12 so we can import it back to the .Net security classes
            var base64encoded = enroll.CreatePFX("", // no password, this is for internal consumption
                PFXExportOptions.PFXExportChainWithRoot);

            // instantiate the target class with the PKCS#12 data (and the empty password)
            return new System.Security.Cryptography.X509Certificates.X509Certificate2(
                System.Convert.FromBase64String(base64encoded), "",
                // mark the private key as exportable (this is usually what you want to do)
                System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.Exportable
            );
        }`

                private void btnGenerate_Click(object sender, EventArgs e)
        {
                X509Certificate2 senderCert = SelfSignedCertificate.CreateX509Certificate2(txtSenderCertName.Text);
                string senderCertFileName = !string.IsNullOrWhiteSpace(txtSenderFileName.Text) ? txtSenderFileName.Text + ".p12" : "sender.p12";
                string senderCertPath = Path.Combine(Properties.Settings.Default.CertificatesPath, senderCertFileName);

                X509Certificate2 receiverCert = SelfSignedCertificate.CreateX509Certificate2(txtReceiverCertName.Text);
                string receiverCertFileName = !string.IsNullOrWhiteSpace(txtReceiverFileName.Text) ? txtReceiverFileName.Text + ".cer" : "receiver.cer";
                string receiverCertPath = Path.Combine(Properties.Settings.Default.CertificatesPath, receiverCertFileName);

                //Grava certificados no disco
                File.WriteAllBytes(senderCertPath, senderCert.Export(X509ContentType.Pkcs12, txtSenderCertPass.Text));
                File.WriteAllBytes(receiverCertPath, receiverCert.Export(X509ContentType.Cert, txtReceiverCertPass.Text));

                }

Someone have a clue what i'm doing wrong?

Thanks in advance.

Best Regards.

**Comment by DanielCrouch** [comment]
Are you just creating a packet and then decrypting the same packet? Meaning you aren't using the self signed certs to send through IDES, correct?

That error is usually going to occur with a key mismatch. If you want some test keys just to play with, you can use the sender and receiver .p12 keys that are in the testpacket.zip file at https://www.irs.gov/Businesses/Corporations/IDES-Data-Transmission-and-File-Preparation. You can use those to just test encrypting and decrypting, but of course they won't actually work for your account in IDES. You can also use a program like Keystore Explorer to do different key functions whether with a .jks or .p12 format.

**Comment by bfaria15093** [comment]
Hi. Thanks for the reply.

Don't know if i got your point.

Let me ask in another way.

How can i create programmatically my own certificates to select in your solution?

![image](https://cloud.githubusercontent.com/assets/3062223/12720682/d4486eb2-c8f3-11e5-9d62-16a383cfe519.png)

**Comment by DanielCrouch** [comment]
I can try the code you had posted. But why would you want to programmatically create them? When it comes to actually using the system to send a file through IDES, you will need to use the files that the certificate authority gives you. If you are just testing before you use the production certificates, you can use those already created test certificates that I had mentioned. Or there are quite a few programs that handle key management (like Keystore Explorer) very simply.

**Comment by bfaria15093** [comment]
"you will need to use the files that the certificate authority gives you" 

I did not know I had to use the files that finances ( Portugal certificate authority ) would give me . I thought I had to create the certificates programmatically. 

So whenever to send a file via IDES have to ask for certificates to certificate authority??

Regards.

**Comment by DanielCrouch** [comment]
Ok, let me back up a little bit. To create an account to send data through IDES, you need to have a public key/certificate. That certificate is going to come from one of the approved Certificate Authorities. We have a listing of those in a few places, but you can find those https://www.irs.gov/Businesses/Corporations/Digital-certificates. So you need to purchase one of those and then upload the public key portion into IDES. You will use the private key portion of that certificate to perform the digital signature process. The private key used here needs to correspond to the public key that was enrolled in IDES. We use the public key to validate the digital signature. So if the signature is not performed with the proper key pair, it will fail validation on our side and you would be issued an error notification. If someone else has already purchased the certificate and enrolled the account, you would then just need to use that certificate for all of your transmissions through IDES. So again no need to program or create anything, just use that certificate for each transmission.

The other item you need is the IRS Public Key, which is the second red arrow on your screen shot above. You can download this from https://www.ides-support.com/. It is a separate button on the header bar there. You will use that for the encryption, we use our private key to decrypt. So again, if the correct public key is not used, we are not able to decrypt and you would be issued an error notification. So no need to create or buy anything for this one, just download and use this for every transmission.

Does that help?

**Comment by bfaria15093** [comment]
Hello Daniel,

I'm sorry for the delayed reply but i was out of office since we've spoke.

Yes, i think that help a lot. Just in case i'll study this a little longer and if i have any doubt i'll come back to you.

Thank you very much for your help.

Best regards,
Bruno Faria

**Comment by DanielCrouch** [comment]
https://www.irs.gov/Businesses/Corporations/International-Data-Exchange-Service

This is the main IDES page on irs.gov. The User Guide and the IDES Resources linked on the right hand side will probably be the most helpful at this point. All of the FATCA XML Schema information is linked there as well. Once you have the data packaging taken care of, the ICMM sections will probably be of more use as that has information on notifications and record level errors and how to deal with things like corrections and voids.
