### ISSUE TITLE
input of the <TaxYear> 

### ISSUE THREAD

**Issue by lbaltazar-github** [IRSgov/IDES-Data-Preparation-Dot-Net#14]
Please consider the following suggestion for a **"new feature"** -> allow the user, to input the <TaxYear> 

Current program code (btnSignXML) uses the string "2014" as a constant(hard-coded) for <TaxYear> information 
- TaxYear information is used to generate the _<XXXXXXXXXX_Metadata.xml>_ file, part of the .zip ("IDES Data Preparation Tool" output file).

When using the "IDES Data Preparation Tool" to "Create a Transmission File" it would be nice, you provide, at the User-Interface, a new dialog-box** enabling the user to input "TaxYear"/(YYYY) data. **

**Comment by MrGeneric** [comment]
Agreed, this shouldn't be hard-coded.

I'd suggest a Tax Year combobox rather than a dialog.

**Comment by lbaltazar-github** [comment]
You're right,  of course it should be a combobox for the Tax Year

-------- Mensagem original --------
De : David <notifications@github.com> 
Data: 04/04/2016  11:21  (GMT+00:00) 
Para: IRSgov/IDES-Data-Preparation-Dot-Net <IDES-Data-Preparation-Dot-Net@noreply.github.com> 
Cc: lbaltazar-github <lbaltazar@mail.com> 
Assunto: Re: [IRSgov/IDES-Data-Preparation-Dot-Net] input of the <TaxYear> 
  (#14) 

Agreed, this shouldn't be hard-coded.

I'd suggest a Tax Year combobox rather than a dialog.

**Comment by DanielCrouch** [comment]
I have added a combobox on the form that will feed into the metadata xml file.

**Comment by MrGeneric** [comment]
Hi Daniel,
Thanks for adding this. 

Would it be possible to make the tax year combobox a little more future proof, something similar to what's below? It will populate the combobox with the current year and the previous two years.

```
private void SetupTaxYearCombobox()
        {
            string[] taxYears = new string[3];
            taxYears[0] = DateTime.Now.AddYears(-2).Year.ToString();
            taxYears[1] = DateTime.Now.AddYears(-1).Year.ToString();
            taxYears[2] = DateTime.Now.Year.ToString();

            cbxTaxYear.Items.AddRange(taxYears);
            cbxTaxYear.SelectedIndex = 1;
        }
```

**Comment by DanielCrouch** [comment]
We have a couple more changes that are coming down the pipeline that will add some extra functionality. Once we can publish the CBC mode changes, there will be a larger update with quite a few more features.

**Comment by MrGeneric** [comment]
Excellent. Interested to see what features are being added.

In my version, I've included an xml validator, a notification view so business users don't have to open the raw xml files, and a basic view of the IDES Gateway inbox and outbox. Happy to share my code if any of that sounds useful.

**Comment by lbaltazar-github** [comment]
Thank you for adding the code implementing the "TaxYear" combo box.

While waiting the announced release supporting the CBC Cypher Mode... 
I think the set of complementary features you mentioned (xml validator, notifications viewer, ..... ) sounds very, very useful:
- the XML validation feature (I believe you check both (1)XML syntax and (2) against the FATCA XML Schema ) seems outstanding
- also  both the "notifications view" and the  "IDES inbox and outbox" features may also be a cause of joy for the business users
