### ISSUE TITLE
Question regarding EncryptAesKey

### ISSUE THREAD

**Issue by gnbAT** [IRSgov/IDES-Data-Preparation-Dot-Net#15]
According to:
https://www.irs.gov/Businesses/Corporations/IDES-Data-Transmission-and-File-Preparation
(Step 2 - Encrypt AES key file - Process Description)

"Encrypt AES key and IV (48 bytes total – 32 byte AES key and 16 byte IV)"

But in Form1.cs line 102, only the aesEncryptionKey is being encrypted:
AesManager.EncryptAesKey(aesEncryptionKey, txtKeyCert.Text, txtKeyCertPassword.Text, encryptedFileName);

Shouldn't aesEncryptionKey be concatenated with aesEncryptionVector to get the 48 byte payload?

Thank you.

**Comment by DanielCrouch** [comment]
We haven't updated the code here for the CBC mode change yet. So what you see here is still all using ECB, which is required up through July 9. We have to test the change internally before we can post it. We are still waiting for a test environment. Right now we are looking at the late April to late May timeframe before we can test and post the updated code. We just want to be sure the encryption and decryption for all the repositories is correct and working with the new change before we post the updates.
