### ISSUE TITLE
Build error in Form1.Designer.cs (dlgOpen_FileOk not defined)

### ISSUE THREAD

**Issue by plaintextcity** [IRSgov/IDES-Data-Preparation-Dot-Net#18]
I downloaded and built the updated application  I used the code downloaded from the archive rather than walking through the gh-pages manually.   I was able to build but I get an error due to one line (error below).  Commenting out the line (which didn't exist int the ECB version) resolves the issue.

Error	1	'WindowsFormsApplication1.MainForm' does not contain a definition for 'dlgOpen_FileOk' and no extension method 'dlgOpen_FileOk' accepting a first argument of type 'WindowsFormsApplication1.MainForm' could be found (are you missing a using directive or an assembly reference?)	d:\MyProjects\SignXML\SignXML\Form1.Designer.cs	309	88	SignXML

**Comment by DanielCrouch** [comment]
I think there was an empty method created for dlgOpen_FileOK. The empty method was not included on the form so that is why the designer form is barking. I removed that line from Form1.Designer.cs and updated the code.
