### ISSUE TITLE
Encrypting Error

### ISSUE THREAD

**Issue by chewzhichao** [IRSgov/IDES-Data-Preparation-Dot-Net#21]
Whenever i tried uploading the encrypted FACTA files to the website (https://wwwpse.idesgateway.com/html/skin/ric/C/login.html), it return the error code RC016 and
my file does not need to apply HCTA key(Model 1 Option 2).
I am already using the C# software from the github link provide by the IDES website (https://github.com/IRSgov/IDES-Data-Preparation-Dot-Net)

**Comment by DanielCrouch** [comment]
The system thinks you should be using the Model 1 Option 2 checkbox. If I understand you correctly, you don't think you need to. If the ISO code portion of your GIIN is for a Model 1 Option 2 jurisdiction, you need to have that checkbox checked. If you aren't sure, I suggest sending an email to lbi.fatca.ides@irs.gov and we can look into your setup over there. But essentially, any account set up for M1O2 needs to use that checkbox on the interface. If your account is not set up for M1O2, you should not use that. It is your GIIN being used to do the submitting that will determine that.

**Comment by chewzhichao** [comment]
Another problem is that whenever I try to solve the RC016 transmission, I encounter the RC004 error...is like I keep getting the same errors RC016 and RC004.

**Comment by DanielCrouch** [comment]
Can you send the metadata from the transmission and the alert email details over to that same lbi.fatca.ides@irs.gov address? There shouldn't be any differences to the metadata for the different model. You can also try the IDES Help Desk at https://www.ides-support.com/Support. They have email support or phone support as well.

**Comment by chewzhichao** [comment]
Is it possible that my file was encrypted using wrong key.

**Comment by DanielCrouch** [comment]
It would have been encrypted with your public key that is enrolled in IDES. There has never been a case where the return file was not encrypted with that enrolled public key.

**Comment by chewzhichao** [comment]
Thank You!!! I manage to encrypted the file
