### ISSUE TITLE
Able to decrypt in test but not able in production

### ISSUE THREAD

**Issue by petertjin** [IRSgov/IDES-Data-Preparation-Dot-Net#24]
During the testing phase, I was able to decrypt the reports that were send to me.
Now that we are doing the same in production, I'm unable to decrypt the reports.

Is the process different for production? Or is the production certificate different?

**Comment by DanielCrouch** [comment]
Yes, the systems are using a different cipher mode and will be until after July 9. Production is still using ECB mode. The test system is using CBC. The test window is set up to allow submitters to test CBC mode before production switches over. If you are using the .Net software, just change the radio button to ECB mode for outgoing data packets and incoming notifications. It will default to CBC mode. Then after July 9th, just leave it set to CBC mode. The keys and certificates are all the same.

**Comment by petertjin** [comment]
Thanks! Using the ECB worked great. Now need to encrypt the file again and do the upload.

Cheers
