### ISSUE TITLE
IDES Response file - Decryption  Failed

### ISSUE THREAD

**Issue by karthik33** [IRSgov/IDES-Data-Preparation-Dot-Net#25]
Hi,

I am getting "the specified key is not a valid size for this algorithm" error while decrypting.

It was running perfectly last year. 
Few days back  our company certificate has been expired. 
So we brought new certificate DegiCert SSL Plus. By using that (.pfx) format I have encrypted our files.
Same certificate after changing to DEP (.cer) format we have uploaded into IDES.
and then we have uploaded our FATCA XML packet into IDES outbox/840 folder.

We received some file in IDES inbox/840, we tried to decrypt we got below error
"the specified key is not a valid size for this algorithm"
I didn't think any code changes required as it is running fine last year and up to last month. 

Can anybody can guide me on this issue please..

I am using   .Net application posted by Github for both encrypting and decrypting

**Comment by DanielCrouch** [comment]
That happens when you use ECB mode on a CBC packet. If you haven't updated your code, you will need to. IDES started using CBC mode instead of ECB mode back on July 9. So any notification that comes to you will be encrypted with CBC. The newest release in the repository has a radio button to select CBC (default) or ECB mode.

**Comment by karthik33** [comment]
Thanks Daniel,
I will follow your instructions and update you, 
Please tell me one point do we need to change anything in our encryption part ?

**Comment by DanielCrouch** [comment]
Yes, the encryption and decryption both require CBC now. The application is updated to send in CBC as well. You don't have to do anything different with the keys or certificates, just make sure the CBC radio button is selected when creating a data packet and when decrypting the notification.

**Comment by karthik33** [comment]
Thanks Dear,  Do you know the link where can I download the .net source code which works for CBC ?
kindly share me if you know. Thanks in advance.

**Comment by DanielCrouch** [comment]
The walkthrough with instructions is located at http://irsgov.github.io/IDES-Data-Preparation-Dot-Net/. This page also has a .zip file that will pull the code.

The releases page also has .zip download links and is located at https://github.com/IRSgov/IDES-Data-Preparation-Dot-Net/releases.

**Comment by MrGeneric** [comment]
@karthik33 I recommended you subscribe to the FATCA newsletter so you find out about these sort of changes in plenty of time.

https://www.irs.gov/individuals/international-taxpayers/subscribe-to-the-fatca-news-and-information-list

**Comment by karthik33** [comment]
sure MrGeneric , Thanks Daniel Crouch
