### ISSUE TITLE
Error with DecryptAesKey

### ISSUE THREAD

**Issue by Stalker3000** [IRSgov/IDES-Data-Preparation-Dot-Net#4]
Try to decrypt uploaded packet. Succesfully unzip. But, when decrypt AES-key, function rsa.Decrypt(payload, false) show dialog window with error "Bad data". 
Our private key and public key have the same md5.

**Comment by DanielCrouch** [comment]
When I have seen that error, it has almost always been an issue with the incorrect private key being used to decrypt. Your public key is going to be used to encrypt the notification that goes back to you. You need to make sure that you have the private key that corresponds to that public key. And that public key will be the current enrolled certificate in IDES. The two most common issues I have seen are that the private key being used is not based off of the current enrolled IDES certificate/public key. So there may have been an update to the certificate in IDES at some point and the private key hasn't been updated. Or the private key is just not correct, and not pulled from the enrolled certificate.

**Comment by karthik33** [comment]
Dear Stalker3000,

I am getting same error while decrypting IDES notification file. I am using the same private key which we uploaded the publick key in IDES Web site. Please help me.

Regards,

**Comment by karthik33** [comment]
Dear Daniel,

can you able to guess my issue ?

**Comment by DanielCrouch** [comment]
https://support.microsoft.com/en-us/kb/951617

You can read a little more about that at the link above. I have seen that error several times and it has always been a key mismatch that has caused it. If you want to run a test, use your public key as the receiver's public key in the encryption process and create a data packet. Instead of sending it through IDES, just use the Decrypt Notification button on the packet that you just created and use your private key as Receiver's Private Key. If that packet you created decrypts successfully and you can see the signed XML, then your key pair should be fine. You would just need to verify that the public key is also the one that is enrolled in IDES and update it if necessary. If you run into an issue, then you have a mismatch on your key pair.

Another test you can try is using our OpenSSL commands (also on Github) to decrypt. If you have trouble decrypting with those as well, then it is just another indicator that there is a key problem.

**Comment by karthik33** [comment]
Dear Daniel,

Thanks for your response.

I have tried your suggestion by encrypting the files using both sender and receiver same certificate which having private key.
But my decryption fail and throw error “Specified key is a not valid size for this algorithm” .


My knowledge on digital certificate is not enough to understand the above issue. Please help how I can resolve.
Is my encryption also having issue ? I am using right certificate?

When I asked my system admin they provided me a certificate they given me with pfx form which having Private key.
How to ensure this certificate is correct for encryption.
If my certificate is wrong what I can ask my system admin to provide correct certificate?

My code throws at the b

Using(AesCryptoServiceProvider aes = new AesCryptoServiceProvider())
{
	Aes.Mode = CipherMode.ECB;
	Aes.key = key ;         ->  failed here ( here my key come with 256 Bytes and try to put in 32 Byte variable and fails)
	Aes.IV = iv;


-	- - - - 

}

Please help in solving the issue.

**Comment by DanielCrouch** [comment]
Try using the sender and receiver .p12 files from the testpacket.zip file we have posted at http://www.irs.gov/Businesses/Corporations/IDES-Data-Transmission-and-File-Preparation. You can use those and see if it encrypts and decrypts properly for you. That at least would rule out the program being set up incorrectly. It doesn't sound like it is, but that may at least rule it out and it would also again point to the key/certificate that you are using that is the issue. 

What Certificate Authority provided the certificate you have and which specific product is it? Is it 2048 bit?

**Comment by DanielCrouch** [comment]
Also, if you have a test packet you can put together, send it over to lbi.fatca.ides@irs.gov. I am curious what the key sizes look like in your encrypted packet. The 32 byte AES key should be 256 once encrypted. So the final packet should show that 256 size for the key. If that is not 256, that is a good indicator that there is a problem as well.

**Comment by DanielCrouch** [comment]
Another also, do you do anything with different operating systems with your files? There was an issue one time with someone who was moving files between linux and windows and a character was being added to the key file causing the byte size to be off. He was using OpenSSL and not our application, but I just wanted to mention it in case there is any movement of files across an OS that may have anything to do with the issue.

I tried using a certificate with a larger 4096 key size, a smaller 1024 key size, a larger SHA2-512 algorithm, a smaller SHA1-128, and even a 4096 key size with a larger 512 algorithm and all 5 were still able to encrypt and decrypt the packet so I dont think it is that anyhow.

**Comment by karthik33** [comment]
Dear Daniel,

For me the TestPacket.Zip alaso having same issue.
I can able to encrypt and create final data packet. But decryption failes.
In Decryption if i select certificate is  reciever certificate from TestPacket

I got "The specified key is a not valid size for this algorithm" got the error

If i used Sender Certificate from Testpacket
I got  "Bad Data" error,(here Key decryption itself failing here).

my system is Windows 7 and 32 Bit OS. is this matters ?
I didn't move from any other OS.

**Comment by DanielCrouch** [comment]
Ok, can you send a couple of things over to the lbi.fatca.ides@irs.gov address? Can you take some screen shots of the interface as you create the data packet using those keys from testpacket.zip? And then some screen shots for the decryption process as well. Also, when you are decrypting, make sure you select a folder location that is empty so that the program doesn't try to grab the wrong key. If you decrypt into a folder full of other keys, it can grab the wrong one since they will be named the same. I have seen the Bad Data error show up when the wrong key file is used. You can just dump the screen shots into a Word document. Send that data packet you create and the screen shots over so we can take a closer look.

**Comment by karthik33** [comment]
Dear Daniel,

Still i struck and could not able to decrypt the IDES message files.
I cross verified my certifiates are correct and no issues in certificates or keys.
I am getting the below error message while decrypting

I am using the same code which github has provided in c#.
Error Message  :  The specified key is not a valid size for this algorithm.
File : AesManager.cs
                                             
Code : ( go to highligted below...here   //  aes.Key => is having 32 bytes, but key has 256 byes )

 public static void DecryptFile(string filePath, string outputFilePath, byte[] key, byte[] iv)
        {
            using (AesCryptoServiceProvider aes = new AesCryptoServiceProvider())
            {
                aes.Mode = CipherMode.ECB;
                aes.Key = key;-----------------------------------------------------------> Error raised here
                aes.IV = iv;

                using (ICryptoTransform cryptoTransform = aes.CreateDecryptor(aes.Key, aes.IV))
                {
                    using (FileStream encrypted = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.Read))
                    {
                        using (FileStream plain = File.Open(outputFilePath, FileMode.Create, FileAccess.Write, FileShare.None))
                        {
                            using (CryptoStream cs = new CryptoStream(plain, cryptoTransform, CryptoStreamMode.Write))
                            {
                                encrypted.CopyTo(cs, bufferSize);
                            }
                        }
                    }
                }
            }
        }

**Comment by paeschr** [comment]
Hi karthik33 could you resolve your problem?

I'm having the problem to.

**Comment by DanielCrouch** [comment]
What Certificate Authority and what product are you using? I am wondering if it is related to a specific certificate. Also, one other thing. When you attempt to decrypt, are you using an empty folder to decrypt into? It may be grabbing the wrong key if you have a folder with other files.

**Comment by paeschr** [comment]
Daniel,

Its entrust certificate SSL advantage. And our internal cert is CA 2003 of Microsoft.

**Comment by paeschr** [comment]
ANY HELP!!!!!!

**Comment by karthik33** [comment]
Hi paeschr,
I can able to decrypt the ides messages now

**Comment by paeschr** [comment]
Hi karthik33,
Was it your keys? or it can with error from IRS.
I just ask because I don't know where to look add.
