### ISSUE TITLE
Code for Submitting IGA Model1 Option2 countries

### ISSUE THREAD

**Issue by kshitijmathur** [IRSgov/IDES-Data-Preparation-Dot-Net#5]
Please update the code for generating the Package for Model1 Option2 countries (which should have 4 files instead of 3 in other cases).

**Comment by DanielCrouch** [comment]
This has been added. Essentially there are a few new input controls on the interface to get the HCTA key and some logic to add the encrypted key into the data packet if the M1O2 checkbox is checked.
