### ISSUE TITLE
Problem with the Certificate Sign

### ISSUE THREAD

**Issue by mcorralesm** [IRSgov/IDES-Data-Preparation-Dot-Net#6]
Hello, we donwloaded the application and built it correctly, we follow every step of the process and we don't see anything wrong with it, but, unfortunedly, we are getting a NSC Notification, is there a way to now a detailed notification about this, because, we already check our Certificate with the one we use on the Enrrollment. By the way, the person taht make the enrrollment is no longer in our institution, and we lost the chance to generate an Administrator end user, is there a way to solve this too?, thanks for further answers to our issues.

**Comment by DanielCrouch** [comment]
You won't get anything that will tell you exactly what the issue is. The two most likely causes are going to be an issue with the keys, some mismatch between what was enrolled and what is being used possibly or that there is an issue with the XML and the signature just wont validate. I haven't seen any problems with the digital signature itself that is created from the application. You can always take the signed Payload file from the program. It should be named _Payload.xml or you can take it from the _Payload.zip file. Both should be available from the processing folder. If you put that in something like Oxygen XML, you can validate the signature and make sure that is not the issue. If it validates there, you should be able to rule that out. If it doesn't and if it is a test file, or you can use a test file, you can send a copy over to lbi.fatca.ides@irs.gov to have someone look at it and see if there is anything obvious or not so obvious that may be causing it. It may be a little harder to verify a problem with the keys. If you need to update your certificate, you will need to do that through the IDES enrollment site. And if you need to have the admin changed or have problems with the enrollment account, you can contact them through the https://www.ides-support.com/Support page there. So regardless of what you find with the digital signature in the file, you should probably contact them to make sure your enrollment account and administrator setup is taken care of.

**Comment by mcorralesm** [comment]
Thanks for the answer, we are going to check on what you are advising us, another institution that had a similar error told us that they check the TimeStamp and make it match in every file, Paylod, Metadata and the name of the ZIP itself, is the a issue with this?, because, the TimeStamp on the files is not exactly the same, there's a difference about miliseconds or seconds. Thanks for your support.

**Comment by DanielCrouch** [comment]
No, that shouldn't matter. I used a hardcoded timestamp in the metadata for a long time and it all worked fine. I think if anyone had an issue and did that to try and fix it, that portion would have just been coincidence and the true fix was elsewhere. Having the correct number of digits in the timestamp is very important, but you would see a different error if it was not formatted correctly.

**Comment by mcorralesm** [comment]
hi again, we already check using Oxigen XML the structure of our XML Payload, and the valide says that is well formed, so, our nest step on the list is to check the Certificate Keys on the IRS Portal, but, unfortunedly, we haven' receive anything from them about the issue we have with the Administrator end user. Hope this can be solved soon. Thanks for the advises.

**Comment by mcorralesm** [comment]
Hi there!, we already send the file and receive the NIM Notification, but, in the IRS site there's no time specified to get a Notification on when we are going to get a Notificaction or Alert about if there's errors or not within the file, is there a time specified for us to wait?, by the way, we didn't get an Alert by email, only by the idesgateway, we checked the configuration of the alerts and the mail account and everything seems to be in order, but, we don't get the email alet yet. Thanks for all your support, if you could give some advises for the alerts pelase.

**Comment by DanielCrouch** [comment]
I believe the record level processing is schedule for the mid-August time frame right now. If you attend any of the Global IT Forum calls that we put on, they usually discuss some of the different business updates such as testing windows and how things are progressing with that record level processing. But expect it to be later in the summer, around August.

I can see some of the notification alert emails going through for you, the RC021 and RC024. But I don't see the initial IDES submission emails. I would start with a contact at the https://www.ides-support.com/Support page or call them at by phone at 1-800-613-IDES (4337) or 605-271-0311. They should be able to double check the account setup and make sure everything looks ok.

**Comment by jaimemorais** [comment]
mcorralesm, DanielCrouch : What was the problem with the signature of the file? We are getting the NSC notification too. We checked the file with the one included in the IDES TestPacket and they are equal. Even the very IDES TestPacket Payload file does not pass in the CheckSignature method of the program.

**Comment by DanielCrouch** [comment]
I didn't see what the end result of the failure was, but just following the thread it appeared to work itself out after the certificates were checked. I haven't seen any files signed by the application fail the signature check and that is why although the check is in there, it isn't being used. As long as there are no changes made to the Payload file after the signature is applied, it should verify without any issues. I usually use something like Oxygen XML or XML Buddy Validator when I need to check a signature. If it verifies with Oxygen, the only times I have seen it not make it through IDES are when the wrong key pair is being used, for example the private key doesn't match the enrolled key in IDES. This happens quite often during the test windows when someone updates a certificate in production and expects the updated certificate to flow through to the test system and it won't do that after the test window has started. But if you are having signature problems, I would start with Oxygen or XML Buddy and see what they show. If they show a valid signature, I would recommend checking the keys being used.

**Comment by jaimemorais** [comment]
How can I check if my certificate is on the test system ?

**Comment by DanielCrouch** [comment]
Any checks for certificates should go through the IDES Support help desk. They have a web contact form at https://www.ides-support.com/Support. Their phone number is also listed at if you prefer to contact them by phone: https://ides.desk.com/customer/portal/articles/1791066-support.

Keep in mind that the way the open test windows work is that all production certificates are copied over to the test system shortly before the opening of the test window. So at that time, the same certificate exists in production and in the test system. But if you update production, there is no mechanism to have that flow through to the test system again. That may not be the case, but it is good to be aware of. But either way, if you need to check certificates, that IDES Support desk is where you need to go.

**Comment by jaimemorais** [comment]
Ok. Thank you. I'll check the file with OxygenXML first.

**Comment by DanielCrouch** [comment]
If you have a test, unencrypted, signed Payload file, we can run it through a validator as well if you don't have one available. If so, you can send it to lbi.fatca.ides@irs.gov for someone to check. If you send it, just add something about "Github" to the subject line.

**Comment by jaimemorais** [comment]
I checked with oxygenXml and find the problem, thank you. It was a problem on our program. 

For the record :
After we signed and get the signed byte array, we loaded it into a new XmlDocument, instead of using File.WriteAllBytes() directly.

Thank you very much Daniel.

**Comment by DanielCrouch** [comment]
Good to hear, thanks for the update.
