### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by shadiakiki1986** [IRSgov/IDES-Data-Preparation-Dot-Net#7]
Hi
I checked out your [github pages](http://irsgov.github.io/IDES-Data-Preparation-Dot-Net/) for your .Net IDES Data Preparation project as well as your Java one, and both seem to describe how to develop the application. Also, there is no csproj file that I can use to compile your project.
* Do you have simple installation instructions, i.e. if I just want to clone, build, and run the application either on windows, linux, or mac?
* Or perhaps do you publish pre-compiled setup files somewhere? 
Thanks

**Comment by DanielCrouch** [comment]
Unfortunately, we aren't able to release it in a compiled, ready to run format. The .zip file attached to the walkthrough does have a lot of the code available and that can save a lot of time with the copy and paste activities though. But you will need to at least make sure everything is where it needs to be before setting up and compiling. And that is why the walkthrough really starts with creating a new project and then adding the different controls and modules into it. And as long as you have VS installed, it really does walk you through setting the entire thing up from scratch.

**Comment by shadiakiki1986** [comment]
It would be very helpful if you can provide a setup file to install this program without having to walk through it from scratch, or at least to include a project file that can be used to build the application
