### ISSUE TITLE
The name 'dlgOpen' does not exist in the current context

### ISSUE THREAD

**Issue by a-harper** [IRSgov/IDES-Data-Preparation-Dot-Net#8]
Hi,

Copy pasted all code (and double checked the repo as well as the tutorial to make sure nothing was different between them) but still getting this error in Form1.cs.
Also getting the same error but for 'dlgOpenFolder'.

Suggestions appreciated!

**Comment by a-harper** [comment]
It would appear that adding:

        OpenFileDialog dlgOpen = new OpenFileDialog();
        FolderBrowserDialog dlgOpenFolder = new FolderBrowserDialog();

Under the public partial class Form1 : Form declaration fixes the issue.

**Comment by DanielCrouch** [comment]
The walkthrough page at http://irsgov.github.io/IDES-Data-Preparation-Dot-Net/ has a table with all of the controls and names. At the bottom of that table are the three dialogue boxes. Make sure you get the save box as well, as that will be used for decrypting notifications.

OpenFileDialog dlgOpen N/A 
SaveFileDialog dlgSave N/A 
FolderBrowserDialog dlgOpenFolder N/A

**Comment by a-harper** [comment]
D'oh! User error! Many thanks.
