### ISSUE TITLE
Problem to decrypt File 

### ISSUE THREAD

**Issue by E6428** [IRSgov/IDES-Data-Preparation-Dot-Net#9]
Hello.

We had receive an IRS notification.
When we try to decrypt it using the software.
We had an error : Invalid Parameter.
The zip is correctly unzip, but that's all.

We use the same .pfx certificate (and password) that had been used to sign the XML file that we had sent to IRS. (it contains private and public key) 
It seems that when we decrypt the key provide by IRS it crashed.

Can you help us to adress this trouble

Best Regards.

R.

**Comment by E6428** [comment]
I've try to use OpenSSL process ... and i've an error too : unable to load Private Key
5692:error:0906D06C:PEM routines:PEM_read_bio:no start line:.\crypto\pem\pem_lib.c:648:Expecting: ANY PRIVATE KEY

**Comment by E6428** [comment]
Find hereafter some additional information :

System.Security.Cryptography.CryptographicException : The parameter is incorrect.
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.RSACryptoServiceProvider.DecryptKey(SafeKeyHandle pKeyContext, Byte[] pbEncryptedKey, Int32 cbEncryptedKey, Boolean fOAEP, ObjectHandleOnStack ohRetDecryptedKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(Byte[] rgb, Boolean fOAEP)

**Comment by paeschr** [comment]
I'M receiving the same problem can someone help please.

**Comment by DanielCrouch** [comment]
You may need to check your key and make sure it is private, and also check the format of it. You may want to take a look at something like http://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6 for example. But those messages are related to key issues.

**Comment by paeschr** [comment]
Daniel,

Its entrust certificate SSL advantage. And our internal cert is CA 2003 of Microsoft.

**Comment by maghazala** [comment]
Hello,
We have applied the IDES Data Preparation - .NET solution, as we have implemented the developed tool and complete the process of Data Preparation successfully, but When we tried to decrypt the notification using the same tool by input the notification zip file and our private key, it doesn't work and gives error "The Parameter is in Correct!" 

And Also, we applied the IDES Data Preparation – Open SSL” for Decrypting notifications received from IDES with OpenSSL, and we are having an issue with the Private Key as it give error “unable to load Private Key”

Please any Advice urgently is very appreciated.

Respects

**Comment by anaraa3** [comment]
I'M receiving the same problem can someone help please.

**Comment by DanielCrouch** [comment]
I think you will probably find this is a problem with your private key file. I am not sure why, but I tried using a windows 10 machine and Keystore Explorer to convert a .jks to a .p12 file and I got the incorrect parameter error. I took the usual .p12 file that was created the same way from a different OS and it worked fine. So you may want to look at how your private key file was created. This could be the OS or possibly how it was exported. I did not try my offending key in OpenSSL, but it may have the same issue.

**Comment by maghazala** [comment]
Exactly, the problem was discovered to be dealing with the private key, as it may be there was any update happened on the private after encrypting the packet, so the problem was solved when re encrypting the file with the updated key and once receiving the notification just decrypt with the same key.
